### ISSUE TITLE
When I have voice chat installed, the server crashes in the console, not in-game.

### ISSUE THREAD

**Issue by Deathyapunk** [MC-U-Team/Voice-Chat#7]
[crash-2021-03-01_19.12.48-server.txt](https://github.com/MC-U-Team/Voice-Chat/files/6062579/crash-2021-03-01_19.12.48-server.txt)

**Comment by HyCraftHD** [comment]
Please use the non dev version

**Comment by Deathyapunk** [comment]
what do you mean by non dev version?
I'm dumb

**Comment by HyCraftHD** [comment]
Download the main version instead of the additional file version
![Uploading image.png…]()

**Comment by HyCraftHD** [comment]
![image](https://user-images.githubusercontent.com/7681220/109519624-b0415500-7aab-11eb-867c-f612673d7181.png)

**Comment by Deathyapunk** [comment]
thanks a lot
